### ISSUE TITLE
Some catches founded

### ISSUE THREAD

**Issue by Abhi1462** [amanjaiman1/GPT_2.0#1]
1. Not answering the question properly
2. Taking too much time to answer the first question

**Comment by amanjaiman1** [comment]
you can correct this from changing in this code

const response = await openai.createCompletion({
      model: "text-davinci-003",
      prompt: `${prompt}`,
      temperature: 0,
      max_tokens: 3000, 
      top_p: 1,
      frequency_penalty: 0.5, 
      presence_penalty: 0,
